"""create opportunities table

Revision ID: 7149e72db894
Revises: d7f4ae2306b4
Create Date: 2026-07-07 19:44:20.863199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7149e72db894'
down_revision: Union[str, Sequence[str], None] = 'd7f4ae2306b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=True),
    sa.Column('demand_score', sa.Integer(), nullable=False),
    sa.Column('competition_score', sa.Integer(), nullable=False),
    sa.Column('buyer_intent_score', sa.Integer(), nullable=False),
    sa.Column('affiliate_score', sa.Integer(), nullable=False),
    sa.Column('pinterest_score', sa.Integer(), nullable=False),
    sa.Column('seo_score', sa.Integer(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_topic'), 'opportunities', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_topic'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
